### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by lalitmee** [spatie/laravel-server-side-rendering#11]
I am facing this issue. Since it is not showing any file to look I don't know where the error is occurring. 
This issue came unexpectedly. I was working the other night, it was working fine and when I run `npm run watch` the next morning, it is showing this error.

```
> @ watch /home/ubuntu/workspace
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

undefined:4
}
^

SyntaxError: Unexpected token } in JSON at position 50
    at Object.parse (native)
    at babelrc (/home/ubuntu/workspace/node_modules/laravel-mix/src/config.js:212:36)
    at global.tap (/home/ubuntu/workspace/node_modules/laravel-mix/src/helpers.js:10:5)
    at Object.babel (/home/ubuntu/workspace/node_modules/laravel-mix/src/config.js:210:13)
    at module.exports (/home/ubuntu/workspace/node_modules/laravel-mix/src/builder/webpack-rules.js:15:33)
    at WebpackConfig.buildRules (/home/ubuntu/workspace/node_modules/laravel-mix/src/builder/WebpackConfig.js:81:41)
    at WebpackConfig.build (/home/ubuntu/workspace/node_modules/laravel-mix/src/builder/WebpackConfig.js:25:14)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/laravel-mix/setup/webpack.config.js:26:38)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/ubuntu/workspace/node_modules/webpack/bin/convert-argv.js:97:18)
```

**Comment by sebastiandedeyne** [comment]
Hi,

Looks like you're have an issue with Laravel Mix or Babel.

I assume you have a syntax error in `.babelrc`. Please open an issue at Babel or Laravel Mix if this isn't resolved, as it has nothing to do with this package.
