### ISSUE TITLE
throw error window is not defined

### ISSUE THREAD

**Issue by lichnow** [spatie/laravel-server-side-rendering#22]
**blade code**
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>vtest</title>
    {{-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'> --}}
    @stack('styles')
    <script defer src="{{ assetic('js/manifest.js','modules/dashboard/frontend') }}"></script>
    <script defer src="{{ assetic('js/vendor.js','modules/dashboard/frontend') }}"></script>
    <script defer src="{{ assetic('js/client.js','modules/dashboard/frontend') }}"></script>
    @stack('scripts')
  </head>
  <body>
    {!! ssr(assetic('js/server.js','modules/dashboard/frontend'))
            ->fallback('<div id="app"></div>')
            ->render() !!}
  </body>
</html>
```
**server.js**
```
import app from './src/main'
import renderServer from 'vue-server-renderer/basic'
app.$router.push(context.url)
renderServer(app, (err, html) => {
    if (err) throw new Error(err)
    dispatch(html)
})
```
**client.js**
```
import app from './src/main'

// app.$router.onReady(() => {
//     app.$mount('#app')
// })
app.$mount('#app')
```
**vue-cli3 && vue.config.js**
```
const path = require('path')
const fs = require('fs')
const fse = require('fs-extra')
const argv = require('yargs').argv
const webpack = require('webpack')
const ManifestPlugin = require('webpack-manifest-plugin')
const _ = require('lodash')

function resolve (dir) {
    return path.join(__dirname, dir)
}

const renderName = _(argv).has('render') ? argv.render : ''
const renderDir = renderName.length > 0 ? `/${renderName}` : ''
const moduleConfig = JSON.parse(fs.readFileSync('module.json', 'utf8'))
const moduleLowerName = _(moduleConfig.name).toLower()
const assetsDir = `modules/${moduleLowerName}${renderDir}`
const assetsUrl = `${assetsDir}/`
const outputPath = path.join('../../public', assetsDir)
const compiler = require(`./render${renderDir}/compiler`)

const params = {
    renderName,
    renderDir,
    moduleConfig,
    moduleLowerName,
    assetsDir,
    assetsUrl,
    outputPath
}

// const getBaseUrl = (host, port) => process.env.NODE_ENV === 'development'
//     ? `http://${host}:${port}/${assetsUrl}` : `/${assetsUrl}`

if (process.env.NODE_ENV === 'development') {
    if (fse.pathExistsSync(outputPath)) fse.removeSync(outputPath)
    let hot = path.join(outputPath, 'hot')
    fse.ensureFileSync(hot)
    fs.chmodSync(hot, '0755')
}
module.exports = {
    baseUrl: `/${assetsUrl}`,
    outputDir: outputPath,
    devServer: {
        publicPath: `http://localhost:8080/${assetsUrl}`,
        headers: {
            'Access-Control-Allow-Origin': '*'
        }
    },
    chainWebpack: config => {
        if (process.env.NODE_ENV === 'development') {
            config.output.publicPath(`http://localhost:8080/${assetsUrl}`)
        }
        config.entryPoints.delete('app')

        config.resolve.alias.set('@', resolve(`render${renderDir}/src`))
        config.module
            .rule('gql')
            .test(/\.(gql|graphql)$/)
            .include
            .add(resolve('render'))
            .add(resolve('test'))
        config.devtool('cheap-module-eval-source-map')

        config.plugins.delete('html')
            .delete('preload')
            .delete('prefetch')
            .end()
            // .plugin('provide')
            // .use(webpack.ProvidePlugin, [{
            //     $: 'jquery',
            //     jQuery: 'jquery',
            //     _: 'lodash'
            // }])
            // .end()
            .plugin('manifest')
            .use(ManifestPlugin, [{
                writeToFileEmit: true,
                filter: ({ isInitial, isModuleAsset }) => {
                    return isInitial && !isModuleAsset
                },
                generate: (seed, files) => files.reduce(
                    (manifest, { name, path }) => {
                        let ext = path.split('.').pop()
                        let key = ext ? `/${ext}/${name}` : `/${name}`
                        return {
                            ...manifest,
                            [key]: process.env.NODE_ENV === 'development'
                                ? path : path.replace(assetsUrl, '')
                        }
                    },
                    seed
                )
            }])
        if (process.env.NODE_ENV === 'production') {
            config.optimization.splitChunks({
                cacheGroups: {
                    vendors: {
                        name: `vendor`,
                        test: /[\\/]node_modules[\\/]/,
                        priority: -10,
                        chunks: 'initial'
                    },
                    common: {
                        name: `common`,
                        minChunks: 2,
                        priority: -20,
                        chunks: 'initial',
                        reuseExistingChunk: true
                    }
                }
            }).runtimeChunk({
                name: 'manifest'
            })
        }
        compiler(config, params)
    }
}
```
**compiler file**
```
module.exports = function (config, { renderDir }) {
    config.entry('client').add(`./render${renderDir}/client.js`)
    config.entry('server').add(`./render${renderDir}/server.js`)
}
```

**assetic function**
```

if (!function_exists('assetic')) {

    function assetic($path, $manifestDirectory = '', $hotLoad = true)
    {
        static $moduleFests = [];
        if (!Str::startsWith($path, '/')) {
            $path = "/{$path}";
        }

        $manifestPath = public_path($manifestDirectory . '/manifest.json');

        if (!isset($moduleFests[$manifestPath])) {
            if (!file_exists($manifestPath))
                throw new Exception('The Mix manifest does not exist.');

            $moduleFests[$manifestPath] = json_decode(file_get_contents($manifestPath), true);
        }

        $manifest = $moduleFests[$manifestPath];

        if (file_exists(public_path($manifestDirectory . '/hot')))
            return !$hotLoad ? null : new HtmlString($manifest[$path]);

        if (!isset($manifest[$path]))
            report(new Exception("Unable to locate Mix file: {$path}."));

        return new HtmlString($manifestDirectory . $manifest[$path]);
    }
}
```

**errors**

7.2.3-1+ubuntu16.04.1+deb.sury.org+1589.49ms6.74MBGET {path?}
The command "/usr/bin/node /home/vagrant/code/gkr/storage/app/ssr/ffeb939d8da979a357015fbda03e1188.js" failed. Exit Code: 1(General error) Working directory: /home/vagrant/code/gkr/public Output: ================ Error Output: ================ /home/vagrant/code/gkr/storage/app/ssr/ffeb939d8da979a357015fbda03e1188.js:1 (function (exports, require, module, __filename, __dirname) { var dispatch = console.log;var process = process || { env: {} };process.env.NODE_ENV = "production";process.env.VUE_ENV = "server";var context = {"url":"\/"};(window["webpackJsonp"]=window["webpackJsonp"]||[]).push([[4],{1:function(e,n,c){e.exports=c("CvHz")},CvHz:function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _src_main__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("a0+3");\n/* harmony import */ var vue_server_renderer_basic__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("kPwN");\n/* harmony import */ var vue_server_renderer_basic__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(vue_server_renderer_basic__WEBPACK_IMPORTED_MODULE_1__);\n\n\n_src_main__WEBPACK_IMPORTED_MODULE_0__[/* default */ "a"].$router.push(context.url);\nvue_server_rende ReferenceError: window is not defined at Object.<anonymous> (/home/vagrant/code/gkr/storage/app/ssr/ffeb939d8da979a357015fbda03e1188.js:1:221) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Function.Module.runMain (module.js:693:10) at startup (bootstrap_node.js:188:16) at bootstrap_node.js:609:3 (View: /home/vagrant/code/gkr/modules/Dashboard/template/views/index.blade.php)
/home/vagrant/code/gkr/vendor/symfony/process/Process.php#223

**Comment by lichnow** [comment]
i found the problem ,that is ` () => import('xxx.vue')`,but how to support it?

**Comment by vaggelis2018** [comment]
even with babel dynamic imports it does not work. Maybe it uses window to add the chunkes which are going to be called on page load.

**Comment by fannyfan414** [comment]
> Got the same issue with `() => import('xxx.vue')`. How do I solve this?
> 
> EDIT:
> Nevermind, the issue is not here. I was able to get past the issue above but there are more things to solve:
> 
> **app-server.js**
> 
> ```
> import app from './app'
> import renderer from 'vue-server-renderer/basic'
> 
> renderer(app, (err, html) => {
> 	console.log(html)
>     if (err) {
>         throw new Error(err);
>     }
> 
>     dispatch(html);
> })
> ```
> 
> The `console.log` returns the actual string of Vue HTML. But the problem is, doing `{!! ssr('js/app-server.js')->render() !!}` in the Blade file doesn't show anything (just empty string, and `console.log` is not even called!).

how did you solve problem with chunks?

**Comment by sentiasa** [comment]
I'm having the same issue, with lazy-loading it doesn't work.

Did any of you guys figure out a solution?

I also asked on SO - https://stackoverflow.com/questions/58216963/lazy-loaded-vue-router-components-dont-work-with-ssr
